
import { Appointment, Employee} from "../types"

export const mockEmployees: Employee[] = [
  {
    id: "E001",
    fullName: "Marco Bianchi",
    role: "Responsabile Manutenzione",
    department: "Manutenzione",
    location: "Stabilimento A",
  },
  {
    id: "E002",
    fullName: "Laura Rossi",
    role: "Quality Engineer",
    department: "Qualità",
    location: "Stabilimento A",
  },
  {
    id: "E003",
    fullName: "Giulia Verdi",
    role: "Production Manager",
    department: "Produzione",
    location: "Stabilimento B",
  },
  {
    id: "E004",
    fullName: "Andrea Neri",
    role: "Logistics Coordinator",
    department: "Logistica",
    location: "Magazzino Centrale",
  },
];

export const mockAppointments: Appointment[] = [
  {
    id: "A001",
    date: "2025-11-25",
    expectedAt: "2025-11-25T08:30:00",
    expectedEnd: "2025-11-25T09:00:00",
    hostId: "E001",
    hostName: "Marco Bianchi",
    visitorName: "John Smith",
    visitorCompany: "DHL Express",
    knownSuspectId: "V001",
    purpose: "Ritiro documenti e verifica area carico",
    location: "Stabilimento A - Ingresso 1",
    status: "scheduled",
  },
  {
    id: "A002",
    date: "2025-11-25",
    expectedAt: "2025-11-25T09:15:00",
    expectedEnd: "2025-11-25T10:00:00",
    hostId: "E002",
    hostName: "Laura Rossi",
    visitorName: "Sarah Johnson",
    visitorCompany: "KUKA Robotics",
    knownSuspectId: "V003",
    purpose: "Audit qualità linea robotizzata",
    location: "Stabilimento A - Sala Riunioni Qualità",
    status: "scheduled",
  },
  {
    id: "A003",
    date: "2025-11-25",
    expectedAt: "2025-11-25T10:00:00",
    expectedEnd: "2025-11-25T11:30:00",
    hostId: "E001",
    hostName: "Marco Bianchi",
    visitorName: "Carlos Lopez",
    visitorCompany: "Siemens",
    knownSuspectId: "V002",
    purpose: "Manutenzione straordinaria quadro elettrico",
    location: "Stabilimento A - Reparto Manutenzione",
    status: "scheduled",
  },
  {
    id: "A004",
    date: "2025-11-25",
    expectedAt: "2025-11-25T11:00:00",
    expectedEnd: "2025-11-25T11:30:00",
    hostId: "E003",
    hostName: "Giulia Verdi",
    visitorName: "Anna Müller",
    visitorCompany: "Bosch",
    knownSuspectId: "V005",
    purpose: "Presentazione nuovi componenti",
    location: "Stabilimento B - Ufficio Produzione",
    status: "scheduled",
  },
  {
    id: "A005",
    date: "2025-11-25",
    expectedAt: "2025-11-25T14:00:00",
    expectedEnd: "2025-11-25T15:00:00",
    hostId: "E004",
    hostName: "Andrea Neri",
    visitorName: "Paolo Conti",
    visitorCompany: "Vigili del Fuoco",
    knownSuspectId: "V004",
    purpose: "Sopralluogo sicurezza uscite di emergenza",
    location: "Magazzino Centrale",
    status: "scheduled",
  },
  {
    id: "A006",
    date: "2025-11-25",
    expectedAt: "2025-11-25T15:30:00",
    expectedEnd: "2025-11-25T16:00:00",
    hostId: "E002",
    hostName: "Laura Rossi",
    visitorName: "Luca Ferri",
    visitorCompany: "ISO Consulting",
    knownSuspectId: null,
    purpose: "Aggiornamento certificazione ISO 9001",
    location: "Stabilimento A - Sala Riunioni 2",
    status: "scheduled",
  },
];
